### ISSUE TITLE
TinyGL for DJGPP/OWv2 32-bit DOS?

### ISSUE THREAD

**Issue by hydexon** [C-Chads/tinygl#17]
There's some plans to port TinyGL for VGA DOS?, like the palette-indexed 8-bit support i was able to crosscompile TinyGL just fine in DJGPP 2.05 but i don't tested it yet unfortunately because it doesn't support 8-bit surfaces, i'm still on the way to integrate it with a special fork of Allegro4, to provide the framebuffer and the texture loading (which is slightly complicated compared with stb_image), probably the way TinyGL push pixels will not efficient because it doesn't use Bresenham's line-drawing algorithm or fixed point arithmetic for FPU-less CPUs which it was common at the time, but i intended to target Pentium 100MHz and MMX systems.

Thanks.

**Comment by gek169** [comment]
We use DDA for lines. This was found to be faster than Bresenham's algorithms.

This fork is not targetted at DOS machines (too little memory to do much anyway!) 

Realistically, DOS machines don't have enough power to tri-rast scenes in 3d in realtime. Quake was about as good as it gets for the OG pentium. Pentium II's could run Quake 2... barely.

i would suggest a custom triangle rasterizer (similar to quake's software renderer) for your game/demo on VGA.

8 bit paletted mode was removed from this codebase because I didn't see much use in trying to use it- it requires more than 64k of memory to do anything anyway. 

I am primarily targetting modern embedded processors, smartphones, and laptops with this fork of TinyGL.

**Comment by hydexon** [comment]
well i was targeting the 32-bit extended modes of DOS using extenders to access at least 16MB of RAM, also my 3D applications would be simplistic geometry for levels, complex models and animations are basically billboard sprites, like DOOM and Duke3D does.

not sure, but oh well thanks i'll see other forks, this fork of TinyGL was the best one from the others which it was more independent from Linux-specific.

Another question: the DDA is a original modification for this fork?, or present in the original codebase of TinyGL?

**Comment by gek169** [comment]
I remember i had to do a huge refactor of the line rendering code, but I do not remember if I replaced the algorithm entirely or if it was using DDA when I came across it.

I do know that I tested the Bresenham line rendering algorithm in a benchmark and it was slower in my tests, so I opted not to use it.

The DDA code also just looks nicer :)

**Comment by gek169** [comment]
(If you have further inquiries, you can post here. Pardon closing the issue)
