### ISSUE TITLE
Expected FPS performance?

### ISSUE THREAD

**Issue by starseeker** [C-Chads/tinygl#7]
Has any benchmarking been done using tinygl and any of the larger Stanford models?  I did a naive swap of the dragon model (assimp conversion of the stl model into an obj) for the extrude.obj and I'm seeing rendering performance of ~0.3 frames per second - was wondering if that is in line with what would be expected for that size of mesh?

**Comment by gek169** [comment]
High polycount models are obviously not going to perform very well.

Without knowing the polycount you rendered the stanford dragon at, i cannot give any indication of expected performance improvement.

**Comment by gek169** [comment]
From my benchmarks, on my i7-6700, I can render about 90,000 to 200,000 lit and textured triangles at 60 frames per second (depending on the conditions and etc)

This is akin to the Playstation 2's GPU in terms of triangle counts.

On higher end Ryzens I was able to get about 2.2x that, mostly due to the larger cache.

**Comment by starseeker** [comment]
OK, that's helpful - thanks!
